export default {
          async fetch(request, env, ctx) {
              const url = new URL(request.url);
                  const currentDomain = url.origin;
                      const targetDomain = 'https://vidcloud.eu.org';

                          // 1. Static Assets (Images/CSS/JS/Fonts) ko Direct Pass Karein (Rate Limit Se Bachne Ke Liye)
                              const pathname = url.pathname.toLowerCase();
                                  if (
                                        pathname.endsWith('.png') || 
                                              pathname.endsWith('.jpg') || 
                                                    pathname.endsWith('.jpeg') || 
                                                          pathname.endsWith('.svg') || 
                                                                pathname.endsWith('.woff2') || 
                                                                      pathname.endsWith('.css')
                                                                          ) {
                                                                                return fetch(targetDomain + url.pathname + url.search, {
                                                                                        headers: {
                                                                                                  'host': 'vidcloud.eu.org',
                                                                                                            'referer': 'https://vidcloud.eu.org/',
                                                                                                                      'user-agent': request.headers.get('user-agent') || 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
                                                                                                                              }
                                                                                                                                    });
                                                                                                                                        }

                                                                                                                                            // 2. CORS Preflight (OPTIONS)
                                                                                                                                                if (request.method === 'OPTIONS') {
                                                                                                                                                      return new Response(null, {
                                                                                                                                                              status: 200,
                                                                                                                                                                      headers: {
                                                                                                                                                                                'access-control-allow-origin': '*',
                                                                                                                                                                                          'access-control-allow-methods': 'GET, POST, PUT, DELETE, OPTIONS',
                                                                                                                                                                                                    'access-control-allow-headers': '*',
                                                                                                                                                                                                              'access-control-max-age': '86400',
                                                                                                                                                                                                                      },
                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                    const targetUrl = targetDomain + url.pathname + url.search;

                                                                                                                                                                                                                                        // Real Browser User-Agent Spoofing
                                                                                                                                                                                                                                            const forwardHeaders = new Headers(request.headers);
                                                                                                                                                                                                                                                forwardHeaders.set('host', 'vidcloud.eu.org');
                                                                                                                                                                                                                                                    forwardHeaders.set('referer', 'https://vidcloud.eu.org/');
                                                                                                                                                                                                                                                        forwardHeaders.set('user-agent', 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36');
                                                                                                                                                                                                                                                            forwardHeaders.delete('accept-encoding');

                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                      const response = await fetch(targetUrl, {
                                                                                                                                                                                                                                                                              method: request.method,
                                                                                                                                                                                                                                                                                      headers: forwardHeaders,
                                                                                                                                                                                                                                                                                              body: request.method !== 'GET' && request.method !== 'HEAD' ? request.body : null,
                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                          const contentType = response.headers.get('content-type') || '';

                                                                                                                                                                                                                                                                                                                // 3. HTML Text Replacements
                                                                                                                                                                                                                                                                                                                      if (contentType.includes('text/html')) {
                                                                                                                                                                                                                                                                                                                              let html = await response.text();

                                                                                                                                                                                                                                                                                                                                      const scriptInjector = `
                                                                                                                                                                                                                                                                                                                                              <script>
                                                                                                                                                                                                                                                                                                                                                        (function() {
                                                                                                                                                                                                                                                                                                                                                                    const myDomain = '${currentDomain}';
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                            const originalFetch = window.fetch;
                                                                                                                                                                                                                                                                                                                                                                                                        window.fetch = function(...args) {
                                                                                                                                                                                                                                                                                                                                                                                                                      if (typeof args[0] === 'string' && args[0].includes('vidcloud.eu.org')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                      args[0] = args[0].replace('https://vidcloud.eu.org', myDomain);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return originalFetch.apply(this, args);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const originalXHR = window.XMLHttpRequest.prototype.open;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      window.XMLHttpRequest.prototype.open = function(method, url, ...rest) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (typeof url === 'string' && url.includes('vidcloud.eu.org')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    url = url.replace('https://vidcloud.eu.org', myDomain);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return originalXHR.call(this, method, url, ...rest);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </head>`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              html = html.replace('</head>', scriptInjector);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      html = html.replaceAll('https://vidcloud.eu.org', currentDomain);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              html = html.replaceAll('vidcloud.eu.org', url.host);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      html = html.replaceAll('Study Stark', 'AURA MAX');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              html = html.replaceAll('VidCloud', 'AURA MAX');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return new Response(html, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status: response.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'content-type': 'text/html; charset=utf-8',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'access-control-allow-origin': '*',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 4. JS & JSON Rewriting
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (contentType.includes('javascript') || contentType.includes('json')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              let text = await response.text();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      text = text.replaceAll('https://vidcloud.eu.org', currentDomain);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text = text.replaceAll('vidcloud.eu.org', url.host);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return new Response(text, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                status: response.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'content-type': contentType,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'access-control-allow-origin': '*',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 5. Media & Other Requests
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const modifiedHeaders = new Headers(response.headers);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modifiedHeaders.set('access-control-allow-origin', '*');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  modifiedHeaders.set('access-control-allow-methods', 'GET, POST, PUT, DELETE, OPTIONS');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        modifiedHeaders.set('access-control-allow-headers', '*',);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Response(response.body, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      status: response.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              headers: modifiedHeaders,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Response('Proxy Error: ' + error.message, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
